### GET order by id
GET http://localhost:9003/orders/1

### POST order data
POST http://localhost:9003/orders/
Content-Type: application/json

{
  "id": "2",
  "customerId": "1",
  "productId": "2",
  "quantity": 3,
  "employeeId": "1",
  "date": "2026-06-09T10:30:00"
}
